/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    faqs: Faq;
    reviews: Review;
    projects: Project;
    rate_limits: RateLimit;
    messages: Message;
    blog: Blog;
    page: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    rate_limits: RateLimitsSelect<false> | RateLimitsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    page: PageSelect<false> | PageSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  position: string;
  review: string;
  image: number | Media;
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  image: number | Media;
  demoUrl: string;
  githubUrl: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate_limits".
 */
export interface RateLimit {
  id: number;
  key: string;
  timestamp: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  email: string;
  message: string;
  ip: string;
  read?: boolean | null;
  type?: ('reply' | 'initial') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  image: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  id: number;
  title: string;
  icon:
    | 'AArrowDown'
    | 'AArrowUp'
    | 'ALargeSmall'
    | 'Accessibility'
    | 'Activity'
    | 'ActivitySquare'
    | 'AirVent'
    | 'Airplay'
    | 'AlarmCheck'
    | 'AlarmClock'
    | 'AlarmClockCheck'
    | 'AlarmClockMinus'
    | 'AlarmClockOff'
    | 'AlarmClockPlus'
    | 'AlarmMinus'
    | 'AlarmPlus'
    | 'AlarmSmoke'
    | 'Album'
    | 'AlertCircle'
    | 'AlertOctagon'
    | 'AlertTriangle'
    | 'AlignCenter'
    | 'AlignCenterHorizontal'
    | 'AlignCenterVertical'
    | 'AlignEndHorizontal'
    | 'AlignEndVertical'
    | 'AlignHorizontalDistributeCenter'
    | 'AlignHorizontalDistributeEnd'
    | 'AlignHorizontalDistributeStart'
    | 'AlignHorizontalJustifyCenter'
    | 'AlignHorizontalJustifyEnd'
    | 'AlignHorizontalJustifyStart'
    | 'AlignHorizontalSpaceAround'
    | 'AlignHorizontalSpaceBetween'
    | 'AlignJustify'
    | 'AlignLeft'
    | 'AlignRight'
    | 'AlignStartHorizontal'
    | 'AlignStartVertical'
    | 'AlignVerticalDistributeCenter'
    | 'AlignVerticalDistributeEnd'
    | 'AlignVerticalDistributeStart'
    | 'AlignVerticalJustifyCenter'
    | 'AlignVerticalJustifyEnd'
    | 'AlignVerticalJustifyStart'
    | 'AlignVerticalSpaceAround'
    | 'AlignVerticalSpaceBetween'
    | 'Ambulance'
    | 'Ampersand'
    | 'Ampersands'
    | 'Amphora'
    | 'Anchor'
    | 'Angry'
    | 'Annoyed'
    | 'Antenna'
    | 'Anvil'
    | 'Aperture'
    | 'AppWindow'
    | 'AppWindowMac'
    | 'Apple'
    | 'Archive'
    | 'ArchiveRestore'
    | 'ArchiveX'
    | 'AreaChart'
    | 'Armchair'
    | 'ArrowBigDown'
    | 'ArrowBigDownDash'
    | 'ArrowBigLeft'
    | 'ArrowBigLeftDash'
    | 'ArrowBigRight'
    | 'ArrowBigRightDash'
    | 'ArrowBigUp'
    | 'ArrowBigUpDash'
    | 'ArrowDown'
    | 'ArrowDown01'
    | 'ArrowDown10'
    | 'ArrowDownAZ'
    | 'ArrowDownAz'
    | 'ArrowDownCircle'
    | 'ArrowDownFromLine'
    | 'ArrowDownLeft'
    | 'ArrowDownLeftFromCircle'
    | 'ArrowDownLeftFromSquare'
    | 'ArrowDownLeftSquare'
    | 'ArrowDownNarrowWide'
    | 'ArrowDownRight'
    | 'ArrowDownRightFromCircle'
    | 'ArrowDownRightFromSquare'
    | 'ArrowDownRightSquare'
    | 'ArrowDownSquare'
    | 'ArrowDownToDot'
    | 'ArrowDownToLine'
    | 'ArrowDownUp'
    | 'ArrowDownWideNarrow'
    | 'ArrowDownZA'
    | 'ArrowDownZa'
    | 'ArrowLeft'
    | 'ArrowLeftCircle'
    | 'ArrowLeftFromLine'
    | 'ArrowLeftRight'
    | 'ArrowLeftSquare'
    | 'ArrowLeftToLine'
    | 'ArrowRight'
    | 'ArrowRightCircle'
    | 'ArrowRightFromLine'
    | 'ArrowRightLeft'
    | 'ArrowRightSquare'
    | 'ArrowRightToLine'
    | 'ArrowUp'
    | 'ArrowUp01'
    | 'ArrowUp10'
    | 'ArrowUpAZ'
    | 'ArrowUpAz'
    | 'ArrowUpCircle'
    | 'ArrowUpDown'
    | 'ArrowUpFromDot'
    | 'ArrowUpFromLine'
    | 'ArrowUpLeft'
    | 'ArrowUpLeftFromCircle'
    | 'ArrowUpLeftFromSquare'
    | 'ArrowUpLeftSquare'
    | 'ArrowUpNarrowWide'
    | 'ArrowUpRight'
    | 'ArrowUpRightFromCircle'
    | 'ArrowUpRightFromSquare'
    | 'ArrowUpRightSquare'
    | 'ArrowUpSquare'
    | 'ArrowUpToLine'
    | 'ArrowUpWideNarrow'
    | 'ArrowUpZA'
    | 'ArrowUpZa'
    | 'ArrowsUpFromLine'
    | 'Asterisk'
    | 'AsteriskSquare'
    | 'AtSign'
    | 'Atom'
    | 'AudioLines'
    | 'AudioWaveform'
    | 'Award'
    | 'Axe'
    | 'Axis3D'
    | 'Axis3d'
    | 'Baby'
    | 'Backpack'
    | 'Badge'
    | 'BadgeAlert'
    | 'BadgeCent'
    | 'BadgeCheck'
    | 'BadgeDollarSign'
    | 'BadgeEuro'
    | 'BadgeHelp'
    | 'BadgeIndianRupee'
    | 'BadgeInfo'
    | 'BadgeJapaneseYen'
    | 'BadgeMinus'
    | 'BadgePercent'
    | 'BadgePlus'
    | 'BadgePoundSterling'
    | 'BadgeRussianRuble'
    | 'BadgeSwissFranc'
    | 'BadgeX'
    | 'BaggageClaim'
    | 'Ban'
    | 'Banana'
    | 'Bandage'
    | 'Banknote'
    | 'BanknoteArrowDown'
    | 'BanknoteArrowUp'
    | 'BanknoteX'
    | 'BarChart'
    | 'BarChart2'
    | 'BarChart3'
    | 'BarChart4'
    | 'BarChartBig'
    | 'BarChartHorizontal'
    | 'BarChartHorizontalBig'
    | 'Barcode'
    | 'Baseline'
    | 'Bath'
    | 'Battery'
    | 'BatteryCharging'
    | 'BatteryFull'
    | 'BatteryLow'
    | 'BatteryMedium'
    | 'BatteryPlus'
    | 'BatteryWarning'
    | 'Beaker'
    | 'Bean'
    | 'BeanOff'
    | 'Bed'
    | 'BedDouble'
    | 'BedSingle'
    | 'Beef'
    | 'Beer'
    | 'BeerOff'
    | 'Bell'
    | 'BellDot'
    | 'BellElectric'
    | 'BellMinus'
    | 'BellOff'
    | 'BellPlus'
    | 'BellRing'
    | 'BetweenHorizonalEnd'
    | 'BetweenHorizonalStart'
    | 'BetweenHorizontalEnd'
    | 'BetweenHorizontalStart'
    | 'BetweenVerticalEnd'
    | 'BetweenVerticalStart'
    | 'BicepsFlexed'
    | 'Bike'
    | 'Binary'
    | 'Binoculars'
    | 'Biohazard'
    | 'Bird'
    | 'Bitcoin'
    | 'Blend'
    | 'Blinds'
    | 'Blocks'
    | 'Bluetooth'
    | 'BluetoothConnected'
    | 'BluetoothOff'
    | 'BluetoothSearching'
    | 'Bold'
    | 'Bolt'
    | 'Bomb'
    | 'Bone'
    | 'Book'
    | 'BookA'
    | 'BookAudio'
    | 'BookCheck'
    | 'BookCopy'
    | 'BookDashed'
    | 'BookDown'
    | 'BookHeadphones'
    | 'BookHeart'
    | 'BookImage'
    | 'BookKey'
    | 'BookLock'
    | 'BookMarked'
    | 'BookMinus'
    | 'BookOpen'
    | 'BookOpenCheck'
    | 'BookOpenText'
    | 'BookPlus'
    | 'BookTemplate'
    | 'BookText'
    | 'BookType'
    | 'BookUp'
    | 'BookUp2'
    | 'BookUser'
    | 'BookX'
    | 'Bookmark'
    | 'BookmarkCheck'
    | 'BookmarkMinus'
    | 'BookmarkPlus'
    | 'BookmarkX'
    | 'BoomBox'
    | 'Bot'
    | 'BotMessageSquare'
    | 'BotOff'
    | 'BowArrow'
    | 'Box'
    | 'BoxSelect'
    | 'Boxes'
    | 'Braces'
    | 'Brackets'
    | 'Brain'
    | 'BrainCircuit'
    | 'BrainCog'
    | 'BrickWall'
    | 'BrickWallFire'
    | 'Briefcase'
    | 'BriefcaseBusiness'
    | 'BriefcaseConveyorBelt'
    | 'BriefcaseMedical'
    | 'BringToFront'
    | 'Brush'
    | 'BrushCleaning'
    | 'Bubbles'
    | 'Bug'
    | 'BugOff'
    | 'BugPlay'
    | 'Building'
    | 'Building2'
    | 'Bus'
    | 'BusFront'
    | 'Cable'
    | 'CableCar'
    | 'Cake'
    | 'CakeSlice'
    | 'Calculator'
    | 'Calendar'
    | 'Calendar1'
    | 'CalendarArrowDown'
    | 'CalendarArrowUp'
    | 'CalendarCheck'
    | 'CalendarCheck2'
    | 'CalendarClock'
    | 'CalendarCog'
    | 'CalendarDays'
    | 'CalendarFold'
    | 'CalendarHeart'
    | 'CalendarMinus'
    | 'CalendarMinus2'
    | 'CalendarOff'
    | 'CalendarPlus'
    | 'CalendarPlus2'
    | 'CalendarRange'
    | 'CalendarSearch'
    | 'CalendarSync'
    | 'CalendarX'
    | 'CalendarX2'
    | 'Camera'
    | 'CameraOff'
    | 'CandlestickChart'
    | 'Candy'
    | 'CandyCane'
    | 'CandyOff'
    | 'Cannabis'
    | 'Captions'
    | 'CaptionsOff'
    | 'Car'
    | 'CarFront'
    | 'CarTaxiFront'
    | 'Caravan'
    | 'Carrot'
    | 'CaseLower'
    | 'CaseSensitive'
    | 'CaseUpper'
    | 'CassetteTape'
    | 'Cast'
    | 'Castle'
    | 'Cat'
    | 'Cctv'
    | 'ChartArea'
    | 'ChartBar'
    | 'ChartBarBig'
    | 'ChartBarDecreasing'
    | 'ChartBarIncreasing'
    | 'ChartBarStacked'
    | 'ChartCandlestick'
    | 'ChartColumn'
    | 'ChartColumnBig'
    | 'ChartColumnDecreasing'
    | 'ChartColumnIncreasing'
    | 'ChartColumnStacked'
    | 'ChartGantt'
    | 'ChartLine'
    | 'ChartNetwork'
    | 'ChartNoAxesColumn'
    | 'ChartNoAxesColumnDecreasing'
    | 'ChartNoAxesColumnIncreasing'
    | 'ChartNoAxesCombined'
    | 'ChartNoAxesGantt'
    | 'ChartPie'
    | 'ChartScatter'
    | 'ChartSpline'
    | 'Check'
    | 'CheckCheck'
    | 'CheckCircle'
    | 'CheckCircle2'
    | 'CheckLine'
    | 'CheckSquare'
    | 'CheckSquare2'
    | 'ChefHat'
    | 'Cherry'
    | 'ChevronDown'
    | 'ChevronDownCircle'
    | 'ChevronDownSquare'
    | 'ChevronFirst'
    | 'ChevronLast'
    | 'ChevronLeft'
    | 'ChevronLeftCircle'
    | 'ChevronLeftSquare'
    | 'ChevronRight'
    | 'ChevronRightCircle'
    | 'ChevronRightSquare'
    | 'ChevronUp'
    | 'ChevronUpCircle'
    | 'ChevronUpSquare'
    | 'ChevronsDown'
    | 'ChevronsDownUp'
    | 'ChevronsLeft'
    | 'ChevronsLeftRight'
    | 'ChevronsLeftRightEllipsis'
    | 'ChevronsRight'
    | 'ChevronsRightLeft'
    | 'ChevronsUp'
    | 'ChevronsUpDown'
    | 'Chrome'
    | 'Church'
    | 'Cigarette'
    | 'CigaretteOff'
    | 'Circle'
    | 'CircleAlert'
    | 'CircleArrowDown'
    | 'CircleArrowLeft'
    | 'CircleArrowOutDownLeft'
    | 'CircleArrowOutDownRight'
    | 'CircleArrowOutUpLeft'
    | 'CircleArrowOutUpRight'
    | 'CircleArrowRight'
    | 'CircleArrowUp'
    | 'CircleCheck'
    | 'CircleCheckBig'
    | 'CircleChevronDown'
    | 'CircleChevronLeft'
    | 'CircleChevronRight'
    | 'CircleChevronUp'
    | 'CircleDashed'
    | 'CircleDivide'
    | 'CircleDollarSign'
    | 'CircleDot'
    | 'CircleDotDashed'
    | 'CircleEllipsis'
    | 'CircleEqual'
    | 'CircleFadingArrowUp'
    | 'CircleFadingPlus'
    | 'CircleGauge'
    | 'CircleHelp'
    | 'CircleMinus'
    | 'CircleOff'
    | 'CircleParking'
    | 'CircleParkingOff'
    | 'CirclePause'
    | 'CirclePercent'
    | 'CirclePlay'
    | 'CirclePlus'
    | 'CirclePower'
    | 'CircleSlash'
    | 'CircleSlash2'
    | 'CircleSlashed'
    | 'CircleSmall'
    | 'CircleStop'
    | 'CircleUser'
    | 'CircleUserRound'
    | 'CircleX'
    | 'CircuitBoard'
    | 'Citrus'
    | 'Clapperboard'
    | 'Clipboard'
    | 'ClipboardCheck'
    | 'ClipboardCopy'
    | 'ClipboardEdit'
    | 'ClipboardList'
    | 'ClipboardMinus'
    | 'ClipboardPaste'
    | 'ClipboardPen'
    | 'ClipboardPenLine'
    | 'ClipboardPlus'
    | 'ClipboardSignature'
    | 'ClipboardType'
    | 'ClipboardX'
    | 'Clock'
    | 'Clock1'
    | 'Clock10'
    | 'Clock11'
    | 'Clock12'
    | 'Clock2'
    | 'Clock3'
    | 'Clock4'
    | 'Clock5'
    | 'Clock6'
    | 'Clock7'
    | 'Clock8'
    | 'Clock9'
    | 'ClockAlert'
    | 'ClockArrowDown'
    | 'ClockArrowUp'
    | 'ClockFading'
    | 'ClockPlus'
    | 'Cloud'
    | 'CloudAlert'
    | 'CloudCog'
    | 'CloudDownload'
    | 'CloudDrizzle'
    | 'CloudFog'
    | 'CloudHail'
    | 'CloudLightning'
    | 'CloudMoon'
    | 'CloudMoonRain'
    | 'CloudOff'
    | 'CloudRain'
    | 'CloudRainWind'
    | 'CloudSnow'
    | 'CloudSun'
    | 'CloudSunRain'
    | 'CloudUpload'
    | 'Cloudy'
    | 'Clover'
    | 'Club'
    | 'Code'
    | 'Code2'
    | 'CodeSquare'
    | 'CodeXml'
    | 'Codepen'
    | 'Codesandbox'
    | 'Coffee'
    | 'Cog'
    | 'Coins'
    | 'Columns'
    | 'Columns2'
    | 'Columns3'
    | 'Columns3Cog'
    | 'Columns4'
    | 'ColumnsSettings'
    | 'Combine'
    | 'Command'
    | 'Compass'
    | 'Component'
    | 'Computer'
    | 'ConciergeBell'
    | 'Cone'
    | 'Construction'
    | 'Contact'
    | 'Contact2'
    | 'ContactRound'
    | 'Container'
    | 'Contrast'
    | 'Cookie'
    | 'CookingPot'
    | 'Copy'
    | 'CopyCheck'
    | 'CopyMinus'
    | 'CopyPlus'
    | 'CopySlash'
    | 'CopyX'
    | 'Copyleft'
    | 'Copyright'
    | 'CornerDownLeft'
    | 'CornerDownRight'
    | 'CornerLeftDown'
    | 'CornerLeftUp'
    | 'CornerRightDown'
    | 'CornerRightUp'
    | 'CornerUpLeft'
    | 'CornerUpRight'
    | 'Cpu'
    | 'CreativeCommons'
    | 'CreditCard'
    | 'Croissant'
    | 'Crop'
    | 'Cross'
    | 'Crosshair'
    | 'Crown'
    | 'Cuboid'
    | 'CupSoda'
    | 'CurlyBraces'
    | 'Currency'
    | 'Cylinder'
    | 'Dam'
    | 'Database'
    | 'DatabaseBackup'
    | 'DatabaseZap'
    | 'DecimalsArrowLeft'
    | 'DecimalsArrowRight'
    | 'Delete'
    | 'Dessert'
    | 'Diameter'
    | 'Diamond'
    | 'DiamondMinus'
    | 'DiamondPercent'
    | 'DiamondPlus'
    | 'Dice1'
    | 'Dice2'
    | 'Dice3'
    | 'Dice4'
    | 'Dice5'
    | 'Dice6'
    | 'Dices'
    | 'Diff'
    | 'Disc'
    | 'Disc2'
    | 'Disc3'
    | 'DiscAlbum'
    | 'Divide'
    | 'DivideCircle'
    | 'DivideSquare'
    | 'Dna'
    | 'DnaOff'
    | 'Dock'
    | 'Dog'
    | 'DollarSign'
    | 'Donut'
    | 'DoorClosed'
    | 'DoorClosedLocked'
    | 'DoorOpen'
    | 'Dot'
    | 'DotSquare'
    | 'Download'
    | 'DownloadCloud'
    | 'DraftingCompass'
    | 'Drama'
    | 'Dribbble'
    | 'Drill'
    | 'Droplet'
    | 'DropletOff'
    | 'Droplets'
    | 'Drum'
    | 'Drumstick'
    | 'Dumbbell'
    | 'Ear'
    | 'EarOff'
    | 'Earth'
    | 'EarthLock'
    | 'Eclipse'
    | 'Edit'
    | 'Edit2'
    | 'Edit3'
    | 'Egg'
    | 'EggFried'
    | 'EggOff'
    | 'Ellipsis'
    | 'EllipsisVertical'
    | 'Equal'
    | 'EqualApproximately'
    | 'EqualNot'
    | 'EqualSquare'
    | 'Eraser'
    | 'EthernetPort'
    | 'Euro'
    | 'Expand'
    | 'ExternalLink'
    | 'Eye'
    | 'EyeClosed'
    | 'EyeOff'
    | 'Facebook'
    | 'Factory'
    | 'Fan'
    | 'FastForward'
    | 'Feather'
    | 'Fence'
    | 'FerrisWheel'
    | 'Figma'
    | 'File'
    | 'FileArchive'
    | 'FileAudio'
    | 'FileAudio2'
    | 'FileAxis3D'
    | 'FileAxis3d'
    | 'FileBadge'
    | 'FileBadge2'
    | 'FileBarChart'
    | 'FileBarChart2'
    | 'FileBox'
    | 'FileChartColumn'
    | 'FileChartColumnIncreasing'
    | 'FileChartLine'
    | 'FileChartPie'
    | 'FileCheck'
    | 'FileCheck2'
    | 'FileClock'
    | 'FileCode'
    | 'FileCode2'
    | 'FileCog'
    | 'FileCog2'
    | 'FileDiff'
    | 'FileDigit'
    | 'FileDown'
    | 'FileEdit'
    | 'FileHeart'
    | 'FileImage'
    | 'FileInput'
    | 'FileJson'
    | 'FileJson2'
    | 'FileKey'
    | 'FileKey2'
    | 'FileLineChart'
    | 'FileLock'
    | 'FileLock2'
    | 'FileMinus'
    | 'FileMinus2'
    | 'FileMusic'
    | 'FileOutput'
    | 'FilePen'
    | 'FilePenLine'
    | 'FilePieChart'
    | 'FilePlus'
    | 'FilePlus2'
    | 'FileQuestion'
    | 'FileScan'
    | 'FileSearch'
    | 'FileSearch2'
    | 'FileSignature'
    | 'FileSliders'
    | 'FileSpreadsheet'
    | 'FileStack'
    | 'FileSymlink'
    | 'FileTerminal'
    | 'FileText'
    | 'FileType'
    | 'FileType2'
    | 'FileUp'
    | 'FileUser'
    | 'FileVideo'
    | 'FileVideo2'
    | 'FileVolume'
    | 'FileVolume2'
    | 'FileWarning'
    | 'FileX'
    | 'FileX2'
    | 'Files'
    | 'Film'
    | 'Filter'
    | 'FilterX'
    | 'Fingerprint'
    | 'FireExtinguisher'
    | 'Fish'
    | 'FishOff'
    | 'FishSymbol'
    | 'Flag'
    | 'FlagOff'
    | 'FlagTriangleLeft'
    | 'FlagTriangleRight'
    | 'Flame'
    | 'FlameKindling'
    | 'Flashlight'
    | 'FlashlightOff'
    | 'FlaskConical'
    | 'FlaskConicalOff'
    | 'FlaskRound'
    | 'FlipHorizontal'
    | 'FlipHorizontal2'
    | 'FlipVertical'
    | 'FlipVertical2'
    | 'Flower'
    | 'Flower2'
    | 'Focus'
    | 'FoldHorizontal'
    | 'FoldVertical'
    | 'Folder'
    | 'FolderArchive'
    | 'FolderCheck'
    | 'FolderClock'
    | 'FolderClosed'
    | 'FolderCode'
    | 'FolderCog'
    | 'FolderCog2'
    | 'FolderDot'
    | 'FolderDown'
    | 'FolderEdit'
    | 'FolderGit'
    | 'FolderGit2'
    | 'FolderHeart'
    | 'FolderInput'
    | 'FolderKanban'
    | 'FolderKey'
    | 'FolderLock'
    | 'FolderMinus'
    | 'FolderOpen'
    | 'FolderOpenDot'
    | 'FolderOutput'
    | 'FolderPen'
    | 'FolderPlus'
    | 'FolderRoot'
    | 'FolderSearch'
    | 'FolderSearch2'
    | 'FolderSymlink'
    | 'FolderSync'
    | 'FolderTree'
    | 'FolderUp'
    | 'FolderX'
    | 'Folders'
    | 'Footprints'
    | 'ForkKnife'
    | 'ForkKnifeCrossed'
    | 'Forklift'
    | 'FormInput'
    | 'Forward'
    | 'Frame'
    | 'Framer'
    | 'Frown'
    | 'Fuel'
    | 'Fullscreen'
    | 'FunctionSquare'
    | 'Funnel'
    | 'FunnelPlus'
    | 'FunnelX'
    | 'GalleryHorizontal'
    | 'GalleryHorizontalEnd'
    | 'GalleryThumbnails'
    | 'GalleryVertical'
    | 'GalleryVerticalEnd'
    | 'Gamepad'
    | 'Gamepad2'
    | 'GanttChart'
    | 'GanttChartSquare'
    | 'Gauge'
    | 'GaugeCircle'
    | 'Gavel'
    | 'Gem'
    | 'Ghost'
    | 'Gift'
    | 'GitBranch'
    | 'GitBranchPlus'
    | 'GitCommit'
    | 'GitCommitHorizontal'
    | 'GitCommitVertical'
    | 'GitCompare'
    | 'GitCompareArrows'
    | 'GitFork'
    | 'GitGraph'
    | 'GitMerge'
    | 'GitPullRequest'
    | 'GitPullRequestArrow'
    | 'GitPullRequestClosed'
    | 'GitPullRequestCreate'
    | 'GitPullRequestCreateArrow'
    | 'GitPullRequestDraft'
    | 'Github'
    | 'Gitlab'
    | 'GlassWater'
    | 'Glasses'
    | 'Globe'
    | 'Globe2'
    | 'GlobeLock'
    | 'Goal'
    | 'Gpu'
    | 'Grab'
    | 'GraduationCap'
    | 'Grape'
    | 'Grid'
    | 'Grid2X2'
    | 'Grid2X2Check'
    | 'Grid2X2Plus'
    | 'Grid2X2X'
    | 'Grid2x2'
    | 'Grid2x2Check'
    | 'Grid2x2Plus'
    | 'Grid2x2X'
    | 'Grid3X3'
    | 'Grid3x3'
    | 'Grip'
    | 'GripHorizontal'
    | 'GripVertical'
    | 'Group'
    | 'Guitar'
    | 'Ham'
    | 'Hamburger'
    | 'Hammer'
    | 'Hand'
    | 'HandCoins'
    | 'HandHeart'
    | 'HandHelping'
    | 'HandMetal'
    | 'HandPlatter'
    | 'Handshake'
    | 'HardDrive'
    | 'HardDriveDownload'
    | 'HardDriveUpload'
    | 'HardHat'
    | 'Hash'
    | 'Haze'
    | 'HdmiPort'
    | 'Heading'
    | 'Heading1'
    | 'Heading2'
    | 'Heading3'
    | 'Heading4'
    | 'Heading5'
    | 'Heading6'
    | 'HeadphoneOff'
    | 'Headphones'
    | 'Headset'
    | 'Heart'
    | 'HeartCrack'
    | 'HeartHandshake'
    | 'HeartMinus'
    | 'HeartOff'
    | 'HeartPlus'
    | 'HeartPulse'
    | 'Heater'
    | 'HelpCircle'
    | 'HelpingHand'
    | 'Hexagon'
    | 'Highlighter'
    | 'History'
    | 'Home'
    | 'Hop'
    | 'HopOff'
    | 'Hospital'
    | 'Hotel'
    | 'Hourglass'
    | 'House'
    | 'HousePlug'
    | 'HousePlus'
    | 'HouseWifi'
    | 'IceCream'
    | 'IceCream2'
    | 'IceCreamBowl'
    | 'IceCreamCone'
    | 'IdCard'
    | 'Image'
    | 'ImageDown'
    | 'ImageMinus'
    | 'ImageOff'
    | 'ImagePlay'
    | 'ImagePlus'
    | 'ImageUp'
    | 'ImageUpscale'
    | 'Images'
    | 'Import'
    | 'Inbox'
    | 'Indent'
    | 'IndentDecrease'
    | 'IndentIncrease'
    | 'IndianRupee'
    | 'Infinity'
    | 'Info'
    | 'Inspect'
    | 'InspectionPanel'
    | 'Instagram'
    | 'Italic'
    | 'IterationCcw'
    | 'IterationCw'
    | 'JapaneseYen'
    | 'Joystick'
    | 'Kanban'
    | 'KanbanSquare'
    | 'KanbanSquareDashed'
    | 'Key'
    | 'KeyRound'
    | 'KeySquare'
    | 'Keyboard'
    | 'KeyboardMusic'
    | 'KeyboardOff'
    | 'Lamp'
    | 'LampCeiling'
    | 'LampDesk'
    | 'LampFloor'
    | 'LampWallDown'
    | 'LampWallUp'
    | 'LandPlot'
    | 'Landmark'
    | 'Languages'
    | 'Laptop'
    | 'Laptop2'
    | 'LaptopMinimal'
    | 'LaptopMinimalCheck'
    | 'Lasso'
    | 'LassoSelect'
    | 'Laugh'
    | 'Layers'
    | 'Layers2'
    | 'Layers3'
    | 'Layout'
    | 'LayoutDashboard'
    | 'LayoutGrid'
    | 'LayoutList'
    | 'LayoutPanelLeft'
    | 'LayoutPanelTop'
    | 'LayoutTemplate'
    | 'Leaf'
    | 'LeafyGreen'
    | 'Lectern'
    | 'LetterText'
    | 'Library'
    | 'LibraryBig'
    | 'LibrarySquare'
    | 'LifeBuoy'
    | 'Ligature'
    | 'Lightbulb'
    | 'LightbulbOff'
    | 'LineChart'
    | 'Link'
    | 'Link2'
    | 'Link2Off'
    | 'Linkedin'
    | 'List'
    | 'ListCheck'
    | 'ListChecks'
    | 'ListCollapse'
    | 'ListEnd'
    | 'ListFilter'
    | 'ListFilterPlus'
    | 'ListMinus'
    | 'ListMusic'
    | 'ListOrdered'
    | 'ListPlus'
    | 'ListRestart'
    | 'ListStart'
    | 'ListTodo'
    | 'ListTree'
    | 'ListVideo'
    | 'ListX'
    | 'Loader'
    | 'Loader2'
    | 'LoaderCircle'
    | 'LoaderPinwheel'
    | 'Locate'
    | 'LocateFixed'
    | 'LocateOff'
    | 'LocationEdit'
    | 'Lock'
    | 'LockKeyhole'
    | 'LockKeyholeOpen'
    | 'LockOpen'
    | 'LogIn'
    | 'LogOut'
    | 'Logs'
    | 'Lollipop'
    | 'Luggage'
    | 'MSquare'
    | 'Magnet'
    | 'Mail'
    | 'MailCheck'
    | 'MailMinus'
    | 'MailOpen'
    | 'MailPlus'
    | 'MailQuestion'
    | 'MailSearch'
    | 'MailWarning'
    | 'MailX'
    | 'Mailbox'
    | 'Mails'
    | 'Map'
    | 'MapPin'
    | 'MapPinCheck'
    | 'MapPinCheckInside'
    | 'MapPinHouse'
    | 'MapPinMinus'
    | 'MapPinMinusInside'
    | 'MapPinOff'
    | 'MapPinPlus'
    | 'MapPinPlusInside'
    | 'MapPinX'
    | 'MapPinXInside'
    | 'MapPinned'
    | 'MapPlus'
    | 'Mars'
    | 'MarsStroke'
    | 'Martini'
    | 'Maximize'
    | 'Maximize2'
    | 'Medal'
    | 'Megaphone'
    | 'MegaphoneOff'
    | 'Meh'
    | 'MemoryStick'
    | 'Menu'
    | 'MenuSquare'
    | 'Merge'
    | 'MessageCircle'
    | 'MessageCircleCode'
    | 'MessageCircleDashed'
    | 'MessageCircleHeart'
    | 'MessageCircleMore'
    | 'MessageCircleOff'
    | 'MessageCirclePlus'
    | 'MessageCircleQuestion'
    | 'MessageCircleReply'
    | 'MessageCircleWarning'
    | 'MessageCircleX'
    | 'MessageSquare'
    | 'MessageSquareCode'
    | 'MessageSquareDashed'
    | 'MessageSquareDiff'
    | 'MessageSquareDot'
    | 'MessageSquareHeart'
    | 'MessageSquareLock'
    | 'MessageSquareMore'
    | 'MessageSquareOff'
    | 'MessageSquarePlus'
    | 'MessageSquareQuote'
    | 'MessageSquareReply'
    | 'MessageSquareShare'
    | 'MessageSquareText'
    | 'MessageSquareWarning'
    | 'MessageSquareX'
    | 'MessagesSquare'
    | 'Mic'
    | 'Mic2'
    | 'MicOff'
    | 'MicVocal'
    | 'Microchip'
    | 'Microscope'
    | 'Microwave'
    | 'Milestone'
    | 'Milk'
    | 'MilkOff'
    | 'Minimize'
    | 'Minimize2'
    | 'Minus'
    | 'MinusCircle'
    | 'MinusSquare'
    | 'Monitor'
    | 'MonitorCheck'
    | 'MonitorCog'
    | 'MonitorDot'
    | 'MonitorDown'
    | 'MonitorOff'
    | 'MonitorPause'
    | 'MonitorPlay'
    | 'MonitorSmartphone'
    | 'MonitorSpeaker'
    | 'MonitorStop'
    | 'MonitorUp'
    | 'MonitorX'
    | 'Moon'
    | 'MoonStar'
    | 'MoreHorizontal'
    | 'MoreVertical'
    | 'Mountain'
    | 'MountainSnow'
    | 'Mouse'
    | 'MouseOff'
    | 'MousePointer'
    | 'MousePointer2'
    | 'MousePointerBan'
    | 'MousePointerClick'
    | 'MousePointerSquareDashed'
    | 'Move'
    | 'Move3D'
    | 'Move3d'
    | 'MoveDiagonal'
    | 'MoveDiagonal2'
    | 'MoveDown'
    | 'MoveDownLeft'
    | 'MoveDownRight'
    | 'MoveHorizontal'
    | 'MoveLeft'
    | 'MoveRight'
    | 'MoveUp'
    | 'MoveUpLeft'
    | 'MoveUpRight'
    | 'MoveVertical'
    | 'Music'
    | 'Music2'
    | 'Music3'
    | 'Music4'
    | 'Navigation'
    | 'Navigation2'
    | 'Navigation2Off'
    | 'NavigationOff'
    | 'Network'
    | 'Newspaper'
    | 'Nfc'
    | 'NonBinary'
    | 'Notebook'
    | 'NotebookPen'
    | 'NotebookTabs'
    | 'NotebookText'
    | 'NotepadText'
    | 'NotepadTextDashed'
    | 'Nut'
    | 'NutOff'
    | 'Octagon'
    | 'OctagonAlert'
    | 'OctagonMinus'
    | 'OctagonPause'
    | 'OctagonX'
    | 'Omega'
    | 'Option'
    | 'Orbit'
    | 'Origami'
    | 'Outdent'
    | 'Package'
    | 'Package2'
    | 'PackageCheck'
    | 'PackageMinus'
    | 'PackageOpen'
    | 'PackagePlus'
    | 'PackageSearch'
    | 'PackageX'
    | 'PaintBucket'
    | 'PaintRoller'
    | 'Paintbrush'
    | 'Paintbrush2'
    | 'PaintbrushVertical'
    | 'Palette'
    | 'Palmtree'
    | 'Panda'
    | 'PanelBottom'
    | 'PanelBottomClose'
    | 'PanelBottomDashed'
    | 'PanelBottomInactive'
    | 'PanelBottomOpen'
    | 'PanelLeft'
    | 'PanelLeftClose'
    | 'PanelLeftDashed'
    | 'PanelLeftInactive'
    | 'PanelLeftOpen'
    | 'PanelRight'
    | 'PanelRightClose'
    | 'PanelRightDashed'
    | 'PanelRightInactive'
    | 'PanelRightOpen'
    | 'PanelTop'
    | 'PanelTopClose'
    | 'PanelTopDashed'
    | 'PanelTopInactive'
    | 'PanelTopOpen'
    | 'PanelsLeftBottom'
    | 'PanelsLeftRight'
    | 'PanelsRightBottom'
    | 'PanelsTopBottom'
    | 'PanelsTopLeft'
    | 'Paperclip'
    | 'Parentheses'
    | 'ParkingCircle'
    | 'ParkingCircleOff'
    | 'ParkingMeter'
    | 'ParkingSquare'
    | 'ParkingSquareOff'
    | 'PartyPopper'
    | 'Pause'
    | 'PauseCircle'
    | 'PauseOctagon'
    | 'PawPrint'
    | 'PcCase'
    | 'Pen'
    | 'PenBox'
    | 'PenLine'
    | 'PenOff'
    | 'PenSquare'
    | 'PenTool'
    | 'Pencil'
    | 'PencilLine'
    | 'PencilOff'
    | 'PencilRuler'
    | 'Pentagon'
    | 'Percent'
    | 'PercentCircle'
    | 'PercentDiamond'
    | 'PercentSquare'
    | 'PersonStanding'
    | 'PhilippinePeso'
    | 'Phone'
    | 'PhoneCall'
    | 'PhoneForwarded'
    | 'PhoneIncoming'
    | 'PhoneMissed'
    | 'PhoneOff'
    | 'PhoneOutgoing'
    | 'Pi'
    | 'PiSquare'
    | 'Piano'
    | 'Pickaxe'
    | 'PictureInPicture'
    | 'PictureInPicture2'
    | 'PieChart'
    | 'PiggyBank'
    | 'Pilcrow'
    | 'PilcrowLeft'
    | 'PilcrowRight'
    | 'PilcrowSquare'
    | 'Pill'
    | 'PillBottle'
    | 'Pin'
    | 'PinOff'
    | 'Pipette'
    | 'Pizza'
    | 'Plane'
    | 'PlaneLanding'
    | 'PlaneTakeoff'
    | 'Play'
    | 'PlayCircle'
    | 'PlaySquare'
    | 'Plug'
    | 'Plug2'
    | 'PlugZap'
    | 'PlugZap2'
    | 'Plus'
    | 'PlusCircle'
    | 'PlusSquare'
    | 'Pocket'
    | 'PocketKnife'
    | 'Podcast'
    | 'Pointer'
    | 'PointerOff'
    | 'Popcorn'
    | 'Popsicle'
    | 'PoundSterling'
    | 'Power'
    | 'PowerCircle'
    | 'PowerOff'
    | 'PowerSquare'
    | 'Presentation'
    | 'Printer'
    | 'PrinterCheck'
    | 'Projector'
    | 'Proportions'
    | 'Puzzle'
    | 'Pyramid'
    | 'QrCode'
    | 'Quote'
    | 'Rabbit'
    | 'Radar'
    | 'Radiation'
    | 'Radical'
    | 'Radio'
    | 'RadioReceiver'
    | 'RadioTower'
    | 'Radius'
    | 'RailSymbol'
    | 'Rainbow'
    | 'Rat'
    | 'Ratio'
    | 'Receipt'
    | 'ReceiptCent'
    | 'ReceiptEuro'
    | 'ReceiptIndianRupee'
    | 'ReceiptJapaneseYen'
    | 'ReceiptPoundSterling'
    | 'ReceiptRussianRuble'
    | 'ReceiptSwissFranc'
    | 'ReceiptText'
    | 'RectangleEllipsis'
    | 'RectangleGoggles'
    | 'RectangleHorizontal'
    | 'RectangleVertical'
    | 'Recycle'
    | 'Redo'
    | 'Redo2'
    | 'RedoDot'
    | 'RefreshCcw'
    | 'RefreshCcwDot'
    | 'RefreshCw'
    | 'RefreshCwOff'
    | 'Refrigerator'
    | 'Regex'
    | 'RemoveFormatting'
    | 'Repeat'
    | 'Repeat1'
    | 'Repeat2'
    | 'Replace'
    | 'ReplaceAll'
    | 'Reply'
    | 'ReplyAll'
    | 'Rewind'
    | 'Ribbon'
    | 'Rocket'
    | 'RockingChair'
    | 'RollerCoaster'
    | 'Rotate3D'
    | 'Rotate3d'
    | 'RotateCcw'
    | 'RotateCcwKey'
    | 'RotateCcwSquare'
    | 'RotateCw'
    | 'RotateCwSquare'
    | 'Route'
    | 'RouteOff'
    | 'Router'
    | 'Rows'
    | 'Rows2'
    | 'Rows3'
    | 'Rows4'
    | 'Rss'
    | 'Ruler'
    | 'RulerDimensionLine'
    | 'RussianRuble'
    | 'Sailboat'
    | 'Salad'
    | 'Sandwich'
    | 'Satellite'
    | 'SatelliteDish'
    | 'SaudiRiyal'
    | 'Save'
    | 'SaveAll'
    | 'SaveOff'
    | 'Scale'
    | 'Scale3D'
    | 'Scale3d'
    | 'Scaling'
    | 'Scan'
    | 'ScanBarcode'
    | 'ScanEye'
    | 'ScanFace'
    | 'ScanHeart'
    | 'ScanLine'
    | 'ScanQrCode'
    | 'ScanSearch'
    | 'ScanText'
    | 'ScatterChart'
    | 'School'
    | 'School2'
    | 'Scissors'
    | 'ScissorsLineDashed'
    | 'ScissorsSquare'
    | 'ScissorsSquareDashedBottom'
    | 'ScreenShare'
    | 'ScreenShareOff'
    | 'Scroll'
    | 'ScrollText'
    | 'Search'
    | 'SearchCheck'
    | 'SearchCode'
    | 'SearchSlash'
    | 'SearchX'
    | 'Section'
    | 'Send'
    | 'SendHorizonal'
    | 'SendHorizontal'
    | 'SendToBack'
    | 'SeparatorHorizontal'
    | 'SeparatorVertical'
    | 'Server'
    | 'ServerCog'
    | 'ServerCrash'
    | 'ServerOff'
    | 'Settings'
    | 'Settings2'
    | 'Shapes'
    | 'Share'
    | 'Share2'
    | 'Sheet'
    | 'Shell'
    | 'Shield'
    | 'ShieldAlert'
    | 'ShieldBan'
    | 'ShieldCheck'
    | 'ShieldClose'
    | 'ShieldEllipsis'
    | 'ShieldHalf'
    | 'ShieldMinus'
    | 'ShieldOff'
    | 'ShieldPlus'
    | 'ShieldQuestion'
    | 'ShieldUser'
    | 'ShieldX'
    | 'Ship'
    | 'ShipWheel'
    | 'Shirt'
    | 'ShoppingBag'
    | 'ShoppingBasket'
    | 'ShoppingCart'
    | 'Shovel'
    | 'ShowerHead'
    | 'Shredder'
    | 'Shrimp'
    | 'Shrink'
    | 'Shrub'
    | 'Shuffle'
    | 'Sidebar'
    | 'SidebarClose'
    | 'SidebarOpen'
    | 'Sigma'
    | 'SigmaSquare'
    | 'Signal'
    | 'SignalHigh'
    | 'SignalLow'
    | 'SignalMedium'
    | 'SignalZero'
    | 'Signature'
    | 'Signpost'
    | 'SignpostBig'
    | 'Siren'
    | 'SkipBack'
    | 'SkipForward'
    | 'Skull'
    | 'Slack'
    | 'Slash'
    | 'SlashSquare'
    | 'Slice'
    | 'Sliders'
    | 'SlidersHorizontal'
    | 'SlidersVertical'
    | 'Smartphone'
    | 'SmartphoneCharging'
    | 'SmartphoneNfc'
    | 'Smile'
    | 'SmilePlus'
    | 'Snail'
    | 'Snowflake'
    | 'SoapDispenserDroplet'
    | 'Sofa'
    | 'SortAsc'
    | 'SortDesc'
    | 'Soup'
    | 'Space'
    | 'Spade'
    | 'Sparkle'
    | 'Sparkles'
    | 'Speaker'
    | 'Speech'
    | 'SpellCheck'
    | 'SpellCheck2'
    | 'Spline'
    | 'SplinePointer'
    | 'Split'
    | 'SplitSquareHorizontal'
    | 'SplitSquareVertical'
    | 'SprayCan'
    | 'Sprout'
    | 'Square'
    | 'SquareActivity'
    | 'SquareArrowDown'
    | 'SquareArrowDownLeft'
    | 'SquareArrowDownRight'
    | 'SquareArrowLeft'
    | 'SquareArrowOutDownLeft'
    | 'SquareArrowOutDownRight'
    | 'SquareArrowOutUpLeft'
    | 'SquareArrowOutUpRight'
    | 'SquareArrowRight'
    | 'SquareArrowUp'
    | 'SquareArrowUpLeft'
    | 'SquareArrowUpRight'
    | 'SquareAsterisk'
    | 'SquareBottomDashedScissors'
    | 'SquareChartGantt'
    | 'SquareCheck'
    | 'SquareCheckBig'
    | 'SquareChevronDown'
    | 'SquareChevronLeft'
    | 'SquareChevronRight'
    | 'SquareChevronUp'
    | 'SquareCode'
    | 'SquareDashed'
    | 'SquareDashedBottom'
    | 'SquareDashedBottomCode'
    | 'SquareDashedKanban'
    | 'SquareDashedMousePointer'
    | 'SquareDashedTopSolid'
    | 'SquareDivide'
    | 'SquareDot'
    | 'SquareEqual'
    | 'SquareFunction'
    | 'SquareGanttChart'
    | 'SquareKanban'
    | 'SquareLibrary'
    | 'SquareM'
    | 'SquareMenu'
    | 'SquareMinus'
    | 'SquareMousePointer'
    | 'SquareParking'
    | 'SquareParkingOff'
    | 'SquarePen'
    | 'SquarePercent'
    | 'SquarePi'
    | 'SquarePilcrow'
    | 'SquarePlay'
    | 'SquarePlus'
    | 'SquarePower'
    | 'SquareRadical'
    | 'SquareRoundCorner'
    | 'SquareScissors'
    | 'SquareSigma'
    | 'SquareSlash'
    | 'SquareSplitHorizontal'
    | 'SquareSplitVertical'
    | 'SquareSquare'
    | 'SquareStack'
    | 'SquareTerminal'
    | 'SquareUser'
    | 'SquareUserRound'
    | 'SquareX'
    | 'SquaresExclude'
    | 'SquaresIntersect'
    | 'SquaresSubtract'
    | 'SquaresUnite'
    | 'Squircle'
    | 'Squirrel'
    | 'Stamp'
    | 'Star'
    | 'StarHalf'
    | 'StarOff'
    | 'Stars'
    | 'StepBack'
    | 'StepForward'
    | 'Stethoscope'
    | 'Sticker'
    | 'StickyNote'
    | 'StopCircle'
    | 'Store'
    | 'StretchHorizontal'
    | 'StretchVertical'
    | 'Strikethrough'
    | 'Subscript'
    | 'Subtitles'
    | 'Sun'
    | 'SunDim'
    | 'SunMedium'
    | 'SunMoon'
    | 'SunSnow'
    | 'Sunrise'
    | 'Sunset'
    | 'Superscript'
    | 'SwatchBook'
    | 'SwissFranc'
    | 'SwitchCamera'
    | 'Sword'
    | 'Swords'
    | 'Syringe'
    | 'Table'
    | 'Table2'
    | 'TableCellsMerge'
    | 'TableCellsSplit'
    | 'TableColumnsSplit'
    | 'TableConfig'
    | 'TableOfContents'
    | 'TableProperties'
    | 'TableRowsSplit'
    | 'Tablet'
    | 'TabletSmartphone'
    | 'Tablets'
    | 'Tag'
    | 'Tags'
    | 'Tally1'
    | 'Tally2'
    | 'Tally3'
    | 'Tally4'
    | 'Tally5'
    | 'Tangent'
    | 'Target'
    | 'Telescope'
    | 'Tent'
    | 'TentTree'
    | 'Terminal'
    | 'TerminalSquare'
    | 'TestTube'
    | 'TestTube2'
    | 'TestTubeDiagonal'
    | 'TestTubes'
    | 'Text'
    | 'TextCursor'
    | 'TextCursorInput'
    | 'TextQuote'
    | 'TextSearch'
    | 'TextSelect'
    | 'TextSelection'
    | 'Theater'
    | 'Thermometer'
    | 'ThermometerSnowflake'
    | 'ThermometerSun'
    | 'ThumbsDown'
    | 'ThumbsUp'
    | 'Ticket'
    | 'TicketCheck'
    | 'TicketMinus'
    | 'TicketPercent'
    | 'TicketPlus'
    | 'TicketSlash'
    | 'TicketX'
    | 'Tickets'
    | 'TicketsPlane'
    | 'Timer'
    | 'TimerOff'
    | 'TimerReset'
    | 'ToggleLeft'
    | 'ToggleRight'
    | 'Toilet'
    | 'Tornado'
    | 'Torus'
    | 'Touchpad'
    | 'TouchpadOff'
    | 'TowerControl'
    | 'ToyBrick'
    | 'Tractor'
    | 'TrafficCone'
    | 'Train'
    | 'TrainFront'
    | 'TrainFrontTunnel'
    | 'TrainTrack'
    | 'TramFront'
    | 'Transgender'
    | 'Trash'
    | 'Trash2'
    | 'TreeDeciduous'
    | 'TreePalm'
    | 'TreePine'
    | 'Trees'
    | 'Trello'
    | 'TrendingDown'
    | 'TrendingUp'
    | 'TrendingUpDown'
    | 'Triangle'
    | 'TriangleAlert'
    | 'TriangleDashed'
    | 'TriangleRight'
    | 'Trophy'
    | 'Truck'
    | 'TruckElectric'
    | 'Turtle'
    | 'Tv'
    | 'Tv2'
    | 'TvMinimal'
    | 'TvMinimalPlay'
    | 'Twitch'
    | 'Twitter'
    | 'Type'
    | 'TypeOutline'
    | 'Umbrella'
    | 'UmbrellaOff'
    | 'Underline'
    | 'Undo'
    | 'Undo2'
    | 'UndoDot'
    | 'UnfoldHorizontal'
    | 'UnfoldVertical'
    | 'Ungroup'
    | 'University'
    | 'Unlink'
    | 'Unlink2'
    | 'Unlock'
    | 'UnlockKeyhole'
    | 'Unplug'
    | 'Upload'
    | 'UploadCloud'
    | 'Usb'
    | 'User'
    | 'User2'
    | 'UserCheck'
    | 'UserCheck2'
    | 'UserCircle'
    | 'UserCircle2'
    | 'UserCog'
    | 'UserCog2'
    | 'UserLock'
    | 'UserMinus'
    | 'UserMinus2'
    | 'UserPen'
    | 'UserPlus'
    | 'UserPlus2'
    | 'UserRound'
    | 'UserRoundCheck'
    | 'UserRoundCog'
    | 'UserRoundMinus'
    | 'UserRoundPen'
    | 'UserRoundPlus'
    | 'UserRoundSearch'
    | 'UserRoundX'
    | 'UserSearch'
    | 'UserSquare'
    | 'UserSquare2'
    | 'UserX'
    | 'UserX2'
    | 'Users'
    | 'Users2'
    | 'UsersRound'
    | 'Utensils'
    | 'UtensilsCrossed'
    | 'UtilityPole'
    | 'Variable'
    | 'Vault'
    | 'Vegan'
    | 'VenetianMask'
    | 'Venus'
    | 'VenusAndMars'
    | 'Verified'
    | 'Vibrate'
    | 'VibrateOff'
    | 'Video'
    | 'VideoOff'
    | 'Videotape'
    | 'View'
    | 'Voicemail'
    | 'Volleyball'
    | 'Volume'
    | 'Volume1'
    | 'Volume2'
    | 'VolumeOff'
    | 'VolumeX'
    | 'Vote'
    | 'Wallet'
    | 'Wallet2'
    | 'WalletCards'
    | 'WalletMinimal'
    | 'Wallpaper'
    | 'Wand'
    | 'Wand2'
    | 'WandSparkles'
    | 'Warehouse'
    | 'WashingMachine'
    | 'Watch'
    | 'Waves'
    | 'WavesLadder'
    | 'Waypoints'
    | 'Webcam'
    | 'Webhook'
    | 'WebhookOff'
    | 'Weight'
    | 'Wheat'
    | 'WheatOff'
    | 'WholeWord'
    | 'Wifi'
    | 'WifiHigh'
    | 'WifiLow'
    | 'WifiOff'
    | 'WifiPen'
    | 'WifiZero'
    | 'Wind'
    | 'WindArrowDown'
    | 'Wine'
    | 'WineOff'
    | 'Workflow'
    | 'Worm'
    | 'WrapText'
    | 'Wrench'
    | 'X'
    | 'XCircle'
    | 'XOctagon'
    | 'XSquare'
    | 'Youtube'
    | 'Zap'
    | 'ZapOff'
    | 'ZoomIn'
    | 'ZoomOut';
  slug: string;
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'rate_limits';
        value: number | RateLimit;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'page';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  review?: T;
  image?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  demoUrl?: T;
  githubUrl?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate_limits_select".
 */
export interface RateLimitsSelect<T extends boolean = true> {
  key?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  ip?: T;
  read?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  content?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  publishedDate?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_select".
 */
export interface PageSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  slug?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}